# Generated by Django 2.1.5 on 2019-01-09 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_imgage', models.CharField(max_length=400)),
                ('title', models.CharField(max_length=48)),
                ('author', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
                ('status', models.CharField(choices=[('available', 'Available'), ('checked-out', 'Checked-out')], default='available', max_length=11)),
                ('date_added', models.DateField(default=datetime.date.today, max_length=30)),
                ('last_borrowed', models.CharField(max_length=4096)),
            ],
        ),
    ]
