# Generated by Django 2.1.5 on 2019-01-09 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lender_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='last_borrowed',
            field=models.DateField(default=datetime.date.today, max_length=30),
        ),
    ]
